version: '3'

services:
  docs:
    image: python_code_interview_local_docs
    container_name: python_code_interview_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./python_code_interview:/app/python_code_interview:z
    ports:
      - '9000:9000'
    command: /start-docs
